name: Hellp world!
env:
  APP_ENV: "dev"
on: 
 push:
   branches:
     - main
 pull_request:
   branches:
     - main
jobs:
  action-demo:
   runs-on: ubuntu-latest
   steps:
     - name: checkout the code
       uses: actions/checkout@v4
     - name: Print index.html
       run: |
        cat index.html
        echo "MY env is $APP_ENV"

  build:
    runs-on: ubuntu-latest
    needs: action-demo
    steps:
      - name: Build step
        run: echo "Hi , ${{ vars.MY_NAME }}"
  
  test:
     runs-on: ubuntu-latest
     needs: build
     steps: 
       - name: test step !
         run: echo "My Password to test the application is ${{ secrets.MY_PASSWORD }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy step !
        run: echo "A deploy step"
